version: '3.9'
services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    command: start --log debug --user "${USER}" --pass "${PW}" memory
    ports:
      - "${PORT}:${PORT}"
    networks:
      - surrealdb-net

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000m

networks:
  surrealdb-net:
    external: true


